

spring:
  rabbitmq:
    host: localhost
    port: 5672
server:
  port: 10082
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false 
management: 
  security:
    enabled: false
